server:
  port: 80
#  servlet:
#    context-path: /webrtc
spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates
    suffix: .html
    cache: false
  web:
    resources:
      static-locations: classpath:/static/